### ISSUE TITLE
TypeError: client.login is not a function.

### ISSUE THREAD

**Issue by TobiWtf** [gastrodon/iMonke.js#2] opened 2020-11-29 08:18 UTC
So, in this snippet, i initialize the client and store it in a memory object

```js
electron.app.on(
    "ready",
    async () => {

        await storage.clear();

        let client = new imonke.Client();

        state.Client = client;

        let createNotLoggedinWindow = async () => {
            menu(
                {
                    needsLogin: true,
                    dev_tools: toolSet,
                },
            );

            CreateWindow(
                "src/monkelogin/monkelogin.html",
            );
        };

        let createLoggedinWindow = async () => {
            menu(
                {
                    needsLogin: false,
                    dev_tools: toolSet,
                },
            );

            CreateWindow(
                "src/monkefeed/monkefeed.html",
            );
        };

        let isLoggedIn = await storage.IsLoggedIn();
        let loginDetails = await storage.GetLogin();

        if (isLoggedIn == false) {
            createNotLoggedinWindow();
        } else {
            let promisedLogin = await client.login(
                {
                    email: loginDetails.email,
                    secret: loginDetails.secret,
                },
            );

            if (promisedLogin == true) {
                storage.SetLogin(
                    await client._email,
                    await client._secret,
                    await client._token,
                );

                createLoggedinWindow();
            } else {
                createNotLoggedinWindow();
            };
        };
    },
);
```

It redirects the user to the login-screen, which should request the client object as seen here

```js
    let client = ipcRenderer.sendSync("get-client");
```

(this is the snippet where it replies)

```js
electron.ipcMain.on(
    "get-client",
    async (event, opts={}) => {
        event.returnValue = state.Client || null;
    },
);
```

At first i thought this was an issue with electron, so i passed the object and printed it when it receives the client, except, it prints a client object as seen here

![Screenshot from 2020-11-29 02-14-43](https://user-images.githubusercontent.com/63171481/100536812-b2fc8780-31e8-11eb-82a3-1f12b4d0f293.png)

So, i examined the class, and cannot find any sign of ``create`` or ``login`` or any of the other class functions, before realizing this was an issue with iMonke.js, however i cant find the issue in the code to resolve it.

**Comment by TobiWtf** [comment] 2020-11-29 08:19
As a side note, the login works fine in the main process, the functions are only stripped as it is passed from the main process to the render, however i havent tried adding the login details to the main process, i will do that and leave an update here.

**Comment by TobiWtf** [comment] 2020-11-29 08:37
another note, processing the the login function works in the main process, passing the initialized class to the render process does not work (i.e event emiting), this is also true of the data field of the client. For those using the client, try to avoid passing the client through an event emiter.

**Comment by gastrodon** [comment] 2020-12-02 20:27
It looks like you're redefining `client` somewhere, or it's going out of scope. What do you get when you `console.log(client)`?

**Comment by gastrodon** [comment] 2020-12-02 20:33
Well, I certainly see that `Client.login` exists, something is changing somewhere. In the scrot you sent I can see it's logging the client properties but no methods, I don't know if that's a symptom, or of methods aren't normally logged. Do any other client methods exist at that point?

**Comment by gastrodon** [comment] 2021-04-12 19:13
Closing because I think this is more likely a symptom of some business in election, and I'm unable to reproduce it. 

If the issue happens again, feel free to open a new issue

**Closed** 2021-04-12 19:13 UTC
Labels: bug
